parameters:
    amf_webservices_client.rest_request.listener.class: AMF\WebServicesClientBundle\Rest\EventListener\RestRequestListener

services:
    amf_webservices_client.rest_request.listener:
        class: %amf_webservices_client.rest_request.listener.class%
        tags:
            - { name: kernel.event_listener, event: amf_webservices_client.rest.request.http_get, method: onGetRequest }
            - { name: kernel.event_listener, event: amf_webservices_client.rest.request.http_post, method: onPostRequest }
            - { name: kernel.event_listener, event: amf_webservices_client.rest.request.http_put, method: onPutRequest }
            - { name: kernel.event_listener, event: amf_webservices_client.rest.request.http_delete, method: onDeleteRequest }
        
