language: php
php:
    - '5.6'
    
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    
before_script:
    - composer install --dev

script:
    - phpunit --coverage-text --coverage-clover=coverage.clover
    
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    email: amine.fattouch@gmail.com
